# Staging
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    email: my@email.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-key
    solvers:
       # An empty 'selector' means that this solver matches all domains
       - selector: { }
         http01:
             ingress: { }

---
# And Production would look something like this
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    email: my@email.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
       # An empty 'selector' means that this solver matches all domains
       - selector: { }
         http01:
             ingress: { }
# DNS challange something like this
#    - dns01:
#       digitalocean:
#         tokenSecretRef:
#            name: digitalocean-dns
#            key: access-token